[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cors>=1.0.1",
    "fastapi>=0.118.0",
    "uvicorn>=0.30.0",
    "requests>=2.31.0",
    "astropy>=6.0.0",
    "pydantic>=2.0.0",
]
